### ISSUE TITLE
NUCLEO-WBA52 board - applications folder missing BLE projects 

### ISSUE THREAD

**Issue by jshroff** [STMicroelectronics/STM32CubeWBA#1]
The 1.4.0 version appears to be missing all the BLE examples for the WBA52 Nucleo board - the older version 1.0 did have those examples

**Comment by RJMSTM** [comment]
Hello @jshroff,

Thanks for your contribution, we no longer support **WBA52**, all connectivity applications are now delivered with **WBA55**.

Regards,
